# Generated by Django 4.2.3 on 2023-07-29 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('generationtime_ms', models.FloatField()),
                ('utc_offset_seconds', models.IntegerField()),
                ('timezone', models.CharField(max_length=100)),
                ('timezone_abbreviation', models.CharField(max_length=10)),
                ('elevation', models.FloatField()),
                ('temperature_2m', models.JSONField()),
                ('relativehumidity_2m', models.JSONField()),
                ('windspeed_10m', models.JSONField()),
            ],
        ),
    ]
